name: 'setup Python and install dependencies'
description: 'This setup Python and Install the required dependencies'
runs:
  using: 'composite'
  steps:
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
