name: Reuseable workflow
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: output info
        run: echo "Deploying and uploading"
  download-artifact:
    needs: run-python-tests
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3