#name: Reusable workflow
#on:
#  workflow_call:
#    inputs:
#      artifact-name:
#        description: The name of the deployable artifact file
#        required: false
#        default: docs
#        type: string
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download artifacts
#        uses: actions/download-artifact@v3
#        with:
#          name: ${{ inputs.artifact-name }}
#
#      - name: Output Information
#        run: echo "Deploying and Uploading...."
