name: actions.yml
on: [push, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

      steps:

        - name: Check out code
          uses: actions/checkout@master

        - name: Set up python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: run test cases
          run: |
            pytest -v -s tests/
        
        - name: upload artifact
          user: actions/upload-artifact@v3
          with:
            name: req-file
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

#    run-test:
#
#      runs-on: ubuntu-latest
#      needs:  [ Build ]
#
#      steps:
#        -
#        - name: run test cases
#          run: |
#            pytest -v -s tests/