name: Trigger Workflow

on:
  push:
    branches: [pytest-framework]


jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow
        run: |
          REPO_OWNER="shubhamlondhe317"
          REPO_NAME="python-api-testing"
          WORKFLOW_NAME="trigger_workflow"

          TOKEN="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"

          curl -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_NAME/dispatches" \
            -d '{"ref":"pytest-framework"}'
